{% set name = "astropy-sphinx-theme" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d2e1d0cbc7c9c38feee12a3c982746f2d6d9d326676af4fb56033cb7f78dc402

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - astropy_sphinx_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/astropy/astropy-sphinx-theme
  summary: The sphinx theme for Astropy and affiliated packages.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - astrofrog
    - drdavella
    - mwcraig
