{% set name = "astropy-sphinx-theme" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9c4d9033cc7df306e2134eceec7597d2950d424e4fe6201f2fbf788e3ceb8b97

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - astropy_sphinx_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/astropy/astropy-sphinx-theme
  summary: The sphinx theme for Astropy and affiliated packages.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - astrofrog
    - drdavella
    - mwcraig
